# Generated by Django 3.0.8 on 2023-01-13 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zone",
            },
        ),
        migrations.CreateModel(
            name="ZoneConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.ManyToManyField(to="core.Country")),
                ("state", models.ManyToManyField(blank=True, to="core.State")),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courier.Zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Connection",
                "verbose_name_plural": "Zone Connection",
            },
        ),
        migrations.CreateModel(
            name="WeightCost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=20)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courier.Zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Weight Cost",
                "verbose_name_plural": "Weight Cost",
            },
        ),
    ]
