# Generated by Django 3.0.8 on 2023-01-13 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourierCountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(blank=True, max_length=10)),
                (
                    "is_domestic",
                    models.BooleanField(
                        default=False,
                        help_text="Domestic destinations can use region-level zones and weight multipliers.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courier Country",
                "verbose_name_plural": "Courier Countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CourierRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=10)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="courier.couriercountry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courier Region",
                "verbose_name_plural": "Courier Regions",
                "ordering": ("country__name", "name"),
                "unique_together": {("country", "name")},
            },
        ),
        migrations.CreateModel(
            name="ZoneConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="zone_connections",
                        to="courier.couriercountry",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="zone_connections",
                        to="courier.courierregion",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="courier.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Connection",
                "verbose_name_plural": "Zone Connections",
            },
        ),
        migrations.CreateModel(
            name="WeightCost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=20)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_costs",
                        to="courier.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weight Cost",
                "verbose_name_plural": "Weight Costs",
                "ordering": ("zone__name", "weight"),
            },
        ),
    ]
